[project]
name = "timelineomat"
version = "0.1.1"
description = ""
authors = [{name = "Alexander Kaftan", email="devkral@web.de"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 80

[tool.hatch.envs.default]
dependencies = ["ruff", "twine"]


[tool.hatch.envs.test]
dependencies = ["faker", "pytest", "timelineomat"]

[tool.hatch.envs.hatch-test]
template = "test"
