[project]
name = "timelineomat"
dynamic = ['version']
description = "Squeeze events into timelines and other timeline manipulations"
authors = [{name = "Alexander Kaftan", email="devkral@web.de"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"
keywords = [
    "event",
    "time",
    "timelines",
    "database",
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
]

[tool.hatch.version]
path = "timelineomat/__init__.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

ignore= ["FA100"]

[tool.hatch.envs.default]
installer = "uv"

[tool.hatch.envs.hatch-test]
dependencies = ["faker", "pytest"]
installer = "uv"

[tool.hatch.envs.hatch-static-analysis]
installer = "uv"
# disables custom ruff rules, required to align with pre-commit
config-path = "none"
dependencies = ["ruff==0.14.2"]
